apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    name: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
    spec:
      tolerations:
      - operator: "Exists"
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 9100
              protocol: TCP